name: Push

on: push

jobs:
  test:
    name: Test and typecheck
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install tabix
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Test codebase
        run: yarn test-ci
      - name: Upload coverage
        uses: codecov/codecov-action@v4
      - name: Typecheck codebase
        run: yarn typecheck

  buildwebsite:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install website deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website
      - name: Build website
        run: |
          cd website/
          yarn build
          mkdir testing
          mv build testing/jb2
      - name: Check website links
        uses: untitaker/hyperlink@0.1.27
        with:
          args: website/testing/ --check-anchors

  buildwholerepo:
    name: Build whole repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Build codebase
        run: yarn build
      - name: Test build
        run: BUILT_TESTS=1 yarn built-test-ci
      - name: Test embedded lgv
        run: |
          yarn
          yarn build
          yarn test:e2e
        working-directory: component_tests/lgv
      - name: Test embedded cgv
        run: |
          yarn
          yarn build
          yarn test:e2e
        working-directory: component_tests/cgv
      - name: Test embedded react-app
        run: |
          yarn
          yarn build
          yarn test:e2e
        working-directory: component_tests/react-app

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint codebase
        run: yarn lint

  formatchecks:
    name: Format/spellcheck/docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Check codebase format
        run: yarn prettier --check .
      - name: Check autogen docs
        run: yarn statedocs && yarn configdocs
      - name: Spellcheck
        uses: crate-ci/typos@master
