name: Push

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  check_commit_message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    outputs:
      skip_jobs: ${{ steps.check_message.outputs.skip_jobs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check commit message
        id: check_message
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          if [[ "$commit_message" == *"[update docs only]"* ]]; then
            echo "skip_jobs=true" >> $GITHUB_OUTPUT
            echo "Commit message contains [update docs only], skipping regular push jobs"
          else
            echo "skip_jobs=false" >> $GITHUB_OUTPUT
            echo "Running regular push jobs"
          fi

  # Conditionally run the buildwebsite job
  buildwebsite:
    name: Build website
    needs: check_commit_message
    if: needs.check_commit_message.outputs.skip_jobs != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install website deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website
      - name: Build website
        run: |
          cd website/
          yarn build
          mkdir testing
          mv build testing/jb2
      - name: Check website links
        uses: untitaker/hyperlink@0.1.27
        with:
          args: website/testing/ --check-anchors

  # Conditionally run the buildwholerepo job
  buildwholerepo:
    name: Build whole repo
    needs: check_commit_message
    if: needs.check_commit_message.outputs.skip_jobs != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Build codebase
        run: yarn build
      - name: Test build
        run: BUILT_TESTS=1 yarn built-test-ci
      - name: Test embedded lgv
        run: |
          yarn
          yarn e2e
        working-directory: component_tests/lgv-vite
      - name: Test embedded cgv
        run: |
          yarn
          yarn e2e
        working-directory: component_tests/cgv-vite
      - name: Test embedded react-app
        run: |
          yarn
          yarn e2e
        working-directory: component_tests/app-vite

  formatchecks:
    name: Lint, typecheck, test
    needs: check_commit_message
    if: needs.check_commit_message.outputs.skip_jobs != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install tabix
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Check codebase format
        run: yarn prettier --check .
      - name: Check autogen docs
        run: yarn statedocs && yarn configdocs
      - name: Spellcheck
        uses: crate-ci/typos@master
      - name: Lint codebase
        run: yarn lint
      - name: Test codebase
        run: yarn test-ci
      - name: Upload coverage
        uses: codecov/codecov-action@v4
      - name: Typecheck codebase
        run: yarn typecheck
